# -*- coding: utf-8 -*-
"""UK security relationships map

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zln0GAAPvGXNqfFsc5xdekVxTIuM4hag
"""

import folium
import requests
from branca.element import Template, MacroElement
from IPython.display import display

print("Initializing UK Security Relationships Map...")

# ---------------------------------------------------
# 1. Initialize map
# -------------------------------------------------
m = folium.Map(location=[20,0], zoom_start=2, tiles="OpenStreetMap")
print("✓ Map initialized")

# ---------------------------------------------------
# 2. Load world GeoJSON with error handling
# ---------------------------------------------------
url = "https://raw.githubusercontent.com/datasets/geo-countries/master/data/countries.geojson"
try:
    response = requests.get(url, timeout=10)
    response.raise_for_status()
    world_geo = response.json()
    print("✓ GeoJSON loaded successfully")
except requests.RequestException as e:
    print(f"✗ Error loading GeoJSON: {e}")
    world_geo = {"features": []}

# ---------------------------------------------------
# 3. Verified UK relationships (accurate 2026)
# ---------------------------------------------------
# Original detailed contexts for specific countries
original_uk_relations_detailed = {
    "United States of America": (
        "Tier 1 Ally",
        """• NATO alliance
• Five Eyes intelligence partnership
• AUKUS security partnership (2021)
• Naval Nuclear Propulsion Cooperation Agreement (2024)""",
        "#003B73" # Deep Navy
    ),
    "Australia": (
        "Major Ally",
        """• Five Eyes intelligence alliance
• AUKUS security partnership (2021)
• UK–Australia AUKUS submarine treaty (2025)""",
        "#0074D9" # Royal Blue
    ),
    "France": (
        "Major Ally",
        """• NATO alliance
• Lancaster House defence treaties
• Combined Joint Expeditionary Force""",
        "#0074D9" # Royal Blue
    ),
    "Germany": (
        "Major Ally",
        """• NATO alliance
• NATO collective defence cooperation""",
        "#0074D9" # Royal Blue
    ),
    "Canada": (
        "Major Ally",
        """• NATO alliance
• Five Eyes intelligence alliance""",
        "#0074D9" # Royal Blue
    ),
    "Poland": (
        "Major Ally",
        """• NATO alliance
• Eastern NATO deterrence cooperation with UK""",
        "#0074D9" # Royal Blue
    ),
    "Japan": (
        "Major Ally",
        """• Hiroshima Accord (2023)
• Global Combat Air Programme – UK-Japan-Italy fighter development""",
        "#0074D9" # Royal Blue
    ),
    "India": (
        "Major Ally",
        """• UK-India Comprehensive Strategic Partnership
• Indo-Pacific security cooperation""",
        "#0074D9" # Royal Blue
    ),
    "Ukraine": (
        "Major Ally",
        """• UK-Ukraine Security Cooperation Agreement (2024)
• Military assistance & training""",
        "#0074D9" # Royal Blue
    ),
    "China": (
        "Strategic Competitor",
        """• Technology and security rivalry""",
        "#F59E0B" # Amber / Orange
    ),
    "Russia": (
        "Adversary",
        """• War in Ukraine
• UK sanctions regime""",
        "#C1121F" # Crimson Red
    ),
    "Iran": (
        "Adversary",
        """• Nuclear programme concerns
• Regional proxy conflicts""",
        "#C1121F" # Crimson Red
    ),
    "North Korea": (
        "Adversary",
        """• Nuclear weapons programme
• UN sanctions""",
        "#C1121F" # Crimson Red
    )
}

# Updated color palette for a new scheme (diplomatic and serious)
relationship_to_color_map = {
    "Tier 1 Ally": "#003B73",   # Deep Navy
    "Major Ally": "#0074D9",   # Royal Blue
    "Partner": "#2E8B57",      # Teal Green
    "Strategic Competitor": "#F59E0B", # Amber / Orange
    "Adversary": "#C1121F",    # Crimson Red
    "Neutral": "#D1D5DB"       # Light Grey
}

# Country name mappings to handle GeoJSON naming conventions
country_name_map = {
    "United States": "United States of America",
    "Korea": "South Korea",
    "South Korea": "South Korea",
    "Türkiye": "Turkey",
    "Turkey": "Turkey",
    "Congo": "Republic of the Congo",
    "DR Congo": "Democratic Republic of the Congo",
    "Democratic Republic of the Congo": "Democratic Republic of the Congo",
    "Republic of the Congo": "Republic of the Congo",
    "Czechia": "Czechia",
    "Czech Republic": "Czechia",
}

default_context = "Standard diplomatic relations"

# User-provided data in markdown table format
user_data_markdown = """
| Country                          | UK Security Relationship |
| -------------------------------- | ------------------------ |
| Afghanistan                      | Neutral                  |
| Albania                          | Major Ally               |
| Algeria                          | Partner                  |
| Andorra                          | Neutral                  |
| Angola                           | Partner                  |
| Antigua and Barbuda              | Partner                  |
| Argentina                        | Partner                  |
| Armenia                          | Partner                  |
| Australia                        | Tier 1 Ally              |
| Austria                          | Partner                  |
| Azerbaijan                       | Partner                  |
| Bahamas                          | Partner                  |
| Bahrain                          | Major Ally               |
| Bangladesh                       | Partner                  |
| Barbados                         | Partner                  |
| Belarus                          | Adversary                |
| Belgium                          | Major Ally               |
| Belize                           | Partner                  |
| Benin                            | Partner                  |
| Bhutan                           | Neutral                  |
| Bolivia                          | Neutral                  |
| Bosnia and Herzegovina           | Partner                  |
| Botswana                         | Partner                  |
| Brazil                           | Partner                  |
| Brunei                           | Major Ally               |
| Bulgaria                         | Major Ally               |
| Burkina Faso                     | Neutral                  |
| Burundi                          | Neutral                  |
| Cabo Verde                       | Partner                  |
| Cambodia                         | Neutral                  |
| Cameroon                         | Partner                  |
| Canada                           | Tier 1 Ally              |
| Central African Republic         | Neutral                  |
| Chad                             | Partner                  |
| Chile                            | Partner                  |
| China                            | Strategic Competitor     |
| Colombia                         | Partner                  |
| Comoros                          | Neutral                  |
| Republic of the Congo            | Partner                  |
| Democratic Republic of the Congo | Partner                  |
| Costa Rica                       | Partner                  |
| Côte d'Ivoire                    | Partner                  |
| Croatia                          | Major Ally               |
| Cuba                             | Neutral                  |
| Cyprus                           | Major Ally               |
| Czechia                          | Major Ally               |
| Denmark                          | Major Ally               |
| Djibouti                         | Partner                  |
| Dominica                         | Partner                  |
| Dominican Republic               | Partner                  |
| Ecuador                          | Partner                  |
| Egypt                            | Partner                  |
| El Salvador                      | Partner                  |
| Equatorial Guinea                | Neutral                  |
| Eritrea                          | Neutral                  |
| Estonia                          | Major Ally               |
| Eswatini                         | Partner                  |
| Ethiopia                         | Partner                  |
| Fiji                             | Partner                  |
| Finland                          | Major Ally               |
| France                           | Tier 1 Ally              |
| Gabon                            | Partner                  |
| Gambia                           | Partner                  |
| Georgia                          | Partner                  |
| Germany                          | Major Ally               |
| Ghana                            | Partner                  |
| Greece                           | Major Ally               |
| Grenada                          | Partner                  |
| Guatemala                        | Partner                  |
| Guinea                           | Neutral                  |
| Guinea-Bissau                    | Neutral                  |
| Guyana                           | Partner                  |
| Haiti                            | Neutral                  |
| Honduras                         | Partner                  |
| Hungary                          | Major Ally               |
| Iceland                          | Major Ally               |
| India                            | Major Ally               |
| Indonesia                        | Partner                  |
| Iran                             | Adversary                |
| Iraq                             | Partner                  |
| Ireland                          | Partner                  |
| Israel                           | Major Ally               |
| Italy                            | Major Ally               |
| Jamaica                          | Partner                  |
| Japan                            | Major Ally               |
| Jordan                           | Major Ally               |
| Kazakhstan                       | Partner                  |
| Kenya                            | Major Ally               |
| Kiribati                         | Partner                  |
| Kosovo                           | Partner                  |
| Kuwait                           | Major Ally               |
| Kyrgyzstan                       | Neutral                  |
| Laos                             | Neutral                  |
| Latvia                           | Major Ally               |
| Lebanon                          | Partner                  |
| Lesotho                          | Partner                  |
| Liberia                          | Partner                  |
| Libya                            | Neutral                  |
| Liechtenstein                    | Neutral                  |
| Lithuania                        | Major Ally               |
| Luxembourg                       | Major Ally               |
| Madagascar                       | Partner                  |
| Malawi                           | Partner                  |
| Malaysia                         | Major Ally               |
| Maldives                         | Partner                  |
| Mali                             | Neutral                  |
| Malta                            | Partner                  |
| Marshall Islands                 | Partner                  |
| Mauritania                       | Partner                  |
| Mauritius                        | Partner                  |
| Mexico                           | Partner                  |
| Micronesia                       | Partner                  |
| Moldova                          | Partner                  |
| Monaco                           | Partner                  |
| Mongolia                         | Partner                  |
| Montenegro                       | Major Ally               |
| Morocco                          | Partner                  |
| Mozambique                       | Partner                  |
| Myanmar                          | Adversary                |
| Namibia                          | Partner                  |
| Nauru                            | Partner                  |
| Nepal                            | Partner                  |
| Netherlands                      | Major Ally               |
| New Zealand                      | Tier 1 Ally              |
| Nicaragua                        | Neutral                  |
| Niger                            | Neutral                  |
| Nigeria                          | Major Ally               |
| North Korea                      | Adversary                |
| North Macedonia                  | Major Ally               |
| Norway                           | Major Ally               |
| Oman                             | Major Ally               |
| Pakistan                         | Major Ally               |
| Palau                            | Partner                  |
| Palestine                        | Neutral                  |
| Panama                           | Partner                  |
| Papua New Guinea                 | Partner                  |
| Paraguay                         | Neutral                  |
| Peru                             | Partner                  |
| Philippines                      | Partner                  |
| Poland                           | Major Ally               |
| Portugal                         | Major Ally               |
| Qatar                            | Major Ally               |
| Romania                          | Major Ally               |
| Russia                           | Adversary                |
| Rwanda                           | Partner                  |
| Saint Kitts and Nevis            | Partner                  |
| Saint Lucia                      | Partner                  |
| Saint Vincent and the Grenadines | Partner                  |
| Samoa                            | Partner                  |
| San Marino                       | Neutral                  |
| São Tomé and Príncipe            | Neutral                  |
| Saudi Arabia                     | Major Ally               |
| Senegal                          | Partner                  |
| Serbia                           | Partner                  |
| Seychelles                       | Partner                  |
| Sierra Leone                     | Partner                  |
| Singapore                        | Major Ally               |
| Slovakia                         | Major Ally               |
| Slovenia                         | Major Ally               |
| Solomon Islands                  | Partner                  |
| Somalia                          | Partner                  |
| South Africa                     | Partner                  |
| South Korea                      | Major Ally               |
| South Sudan                      | Neutral                  |
| Spain                            | Major Ally               |
| Sri Lanka                        | Partner                  |
| Sudan                            | Neutral                  |
| Suriname                         | Neutral                  |
| Sweden                           | Major Ally               |
| Switzerland                      | Partner                  |
| Syria                            | Adversary                |
| Taiwan                           | Partner                  |
| Tajikistan                       | Neutral                  |
| Tanzania                         | Partner                  |
| Thailand                         | Partner                  |
| Timor-Leste                      | Neutral                  |
| Togo                             | Partner                  |
| Tonga                            | Partner                  |
| Trinidad and Tobago              | Partner                  |
| Tunisia                          | Partner                  |
| Türkiye                          | Major Ally               |
| Turkmenistan                     | Neutral                  |
| Tuvalu                           | Partner                  |
| Uganda                           | Partner                  |
| Ukraine                          | Major Ally               |
| United Arab Emirates             | Major Ally               |
| United States                    | Tier 1 Ally              |
| Uruguay                          | Partner                  |
| Uzbekistan                       | Partner                  |
| Vanuatu                          | Partner                  |
| Vatican City                     | Neutral                  |
| Venezuela                        | Strategic Competitor     |
| Vietnam                          | Partner                  |
| Yemen                            | Neutral                  |
| Zambia                           | Partner                  |
| Zimbabwe                         | Neutral                  |
"""

def parse_markdown_table(table_string):
    """Parse markdown table into list of dictionaries"""
    lines = table_string.strip().split('\n')
    if len(lines) < 3:
        return []

    headers = [h.strip() for h in lines[0].strip('|').split('|')]
    data_rows = lines[2:]  # Skip header and separator line

    parsed_data = []
    for row in data_rows:
        if not row.strip():  # Skip empty rows
            continue
        values = [v.strip() for v in row.strip('|').split('|')]
        if len(values) == len(headers):
            parsed_data.append(dict(zip(headers, values)))
    return parsed_data

user_data_list = parse_markdown_table(user_data_markdown)
print(f"✓ Parsed {len(user_data_list)} countries from markdown table")

uk_relations = {}

for item in user_data_list:
    country_name = item["Country"]
    # Apply country name mapping
    mapped_name = country_name_map.get(country_name, country_name)
    new_status = item["UK Security Relationship"]
    new_color = relationship_to_color_map.get(new_status, "#D1D5DB")

    current_entry = original_uk_relations_detailed.get(mapped_name)
    if current_entry and current_entry[0] == new_status:
        # If country exists in original detailed relations and status is the same, keep original context
        new_context = current_entry[1]
    else:
        # New country, or relationship changed, use default context
        new_context = default_context

    uk_relations[mapped_name] = (new_status, new_context, new_color)

print(f"✓ Built UK relations dictionary with {len(uk_relations)} countries")

# ---------------------------------------------------
# 4. Apply relationships to GeoJSON features
# ---------------------------------------------------
matched_countries = 0
for feature in world_geo.get("features", []):
    name = feature["properties"].get("name")
    if name in uk_relations:
        status, context, color = uk_relations[name]
        matched_countries += 1
    else:
        status, context, color = "Neutral", "Standard diplomatic relations", "#D1D5DB"
    
    feature["properties"]["status"] = status
    feature["properties"]["context"] = context
    feature["properties"]["color"] = color

print(f"✓ Matched {matched_countries} countries to GeoJSON features")

# -------------------------------------------------
# 5. Country layer with hover tooltip
# -------------------------------------------------
country_layer = folium.FeatureGroup(name="Country Relationships")

def style_function(feature):
    """Apply styling based on relationship status"""
    fill_color = feature["properties"]["color"]
    fill_opacity_value = 0.7  # Semi-transparent fill by default

    if feature["properties"]["status"] == "Neutral":
        fill_color = "#D1D5DB"  # Light Grey for neutral fill
        fill_opacity_value = 0.9  # Visible but low emphasis

    return {
        "fillColor": fill_color,
        "color": None,  # No outline
        "weight": 0,  # No weight since no outline
        "fillOpacity": fill_opacity_value
    }

def highlight_function(feature):
    """Apply solid fill on hover"""
    fill_color = feature["properties"]["color"]
    fill_opacity_value = 1
    return {
        "fillColor": fill_color,
        "color": None,
        "weight": 0,
        "fillOpacity": fill_opacity_value
    }

tooltip = folium.GeoJsonTooltip(
    fields=["name", "status", "context"],
    aliases=["Country", "Relationship", "Security / Policy Anchors"]
)

folium.GeoJson(
    world_geo,
    style_function=style_function,
    tooltip=tooltip,
    highlight_function=highlight_function
).add_to(country_layer)

country_layer.add_to(m)
print("✓ Country layer added to map")

# ---------------------------------------------------
# 6. Title and Legend Panel
# ---------------------------------------------------
template = """
{% macro html(this, kwargs) %}
<div style="
position: fixed;
top: 10px;
left: 10px;
width: 320px;
background-color: #F8FAFC;
border-radius: 10px;
padding: 15px;
z-index:9999;
font-size:13px;
font-family: Arial;
border:2px solid #CBD5E1;
box-shadow: 3px 3px 8px rgba(0,0,0,0.2);
color: #1F2937;
">
  <div style="background-color: #0F172A; padding: 10px; margin: -15px -15px 15px -15px; border-top-left-radius: 10px; border-top-right-radius: 10px;">
    <h3 style="color: #F8FAFC; margin: 0; padding: 0;">Global Security Relationships</h3>
    <b style="color: #CBD5E1; font-size:12px;">UK Strategic Perspective</b>
  </div>
  <p style="font-size:12px; color: #1F2937;">
  Hover over a country to see its relationship with the UK,
  including verified treaties, agreements, or policy anchors.
  </p>
  <hr style="border-color: #CBD5E1;">
  <b>Relationship Categories</b><br>
  <span style="color:#003B73;">●</span> Tier 1 Ally<br>
  <span style="color:#0074D9;">●</span> Major Ally<br>
  <span style="color:#2E8B57;">●</span> Partner<br>
  <span style="color:#F59E0B;">●</span> Strategic Competitor<br>
  <span style="color:#C1121F;">●</span> Adversary<br>
  <span style="color:#D1D5DB;">●</span> Neutral<br>
  <hr style="border-color: #CBD5E1;">
  <p style="font-size:11px; color: #1F2937;">
  Security Relationship from UK Perspective<br>
  <b>By Abiona Uthera</b>
  </p>
  <p style="font-size:11px; color: #1F2937;">
  GitHub: <a href="https://github.com/abiona324/1" target="_blank" style="color: #007bff; text-decoration: none;">Repository Link</a>
  </p>
</div>
{% endmacro %}
"""

macro = MacroElement()
macro._template = Template(template)
m.get_root().add_child(macro)
print("✓ Legend and title panel added")

# ---------------------------------------------------
# 7. Display and save map
# ---------------------------------------------------
display(m)
m.save("uk_security_map.html")
print("✓ Map saved to uk_security_map.html")
print("\n✓ Map generation complete!")
